# Generated by Django 6.0.1 on 2026-02-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='speed',
            field=models.IntegerField(default=1),
        ),
    ]
