# Generated by Django 6.0.1 on 2026-02-04 13:33

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_player_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='danger_fields',
            field=models.JSONField(default=game.models.generate_danger_fields),
        ),
    ]
