# Generated by Django 6.0.3 on 2026-04-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
